name: Render GitHub stats images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create output folder
        run: mkdir -p assets

           - name: Download stats cards (with token)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L "https://github-readme-stats.vercel.app/api?username=shakeel-Ahamed-A&show_icons=true&theme=tokyonight&token=${GH_TOKEN}" -o assets/stats.svg
          curl -L "https://streak-stats.demolab.com?user=shakeel-Ahamed-A&theme=tokyonight" -o assets/streak.svg
          curl -L "https://github-readme-stats.vercel.app/api/top-langs/?username=shakeel-Ahamed-A&layout=compact&theme=tokyonight&token=${GH_TOKEN}" -o assets/top-langs.svg
      - name: Commit & push (only if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update stats images"
          git push
